### ISSUE TITLE
displaying a single label on duplicated x-axis causes R session to crash on Windows machine

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidyverse/ggplot2#4346]
If I run the following code **only** on my Windows machine (never happens on my Mac), the R session crashes:

```r
library(ggplot2)

ggplot(mtcars, aes(wt, mpg)) + geom_point() +
  ggplot2::scale_x_continuous(
    sec.axis = ggplot2::dup_axis(
      name = NULL,
      labels = parse(text = list("widehat(mu)[median]=='3.32'")),
      breaks = median(mtcars$wt)
    )
  )
```

But the weird thing is that if I try to create a `reprex`, it works!

And produces the following warning messages:

```r
#> Warning in min(x): no non-missing arguments to min; returning Inf
#> Warning in max(x): no non-missing arguments to max; returning -Inf
```

So I made a screen-capture video to catch this behavior:

![ggplot2_crash](https://user-images.githubusercontent.com/11330453/107747686-23ab3e80-6d18-11eb-94a6-e80099374659.gif)

**Comment by IndrajeetPatil** [comment]
Also posting a `reprex` with session info in case it helps in diagnosing the source of this behavior:

``` r
library(ggplot2)

ggplot(mtcars, aes(wt, mpg)) + geom_point() +
  ggplot2::scale_x_continuous(
    sec.axis = ggplot2::dup_axis(
      name = NULL,
      labels = parse(text = list("widehat(mu)[median]=='3.32'")),
      breaks = median(mtcars$wt)
    )
  )
#> Warning in min(x): no non-missing arguments to min; returning Inf
#> Warning in max(x): no non-missing arguments to max; returning -Inf
```

![](https://i.imgur.com/cE0luQM.png)

<sup>Created on 2021-02-12 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                                             
#>  version  R Under development (unstable) (2021-01-13 r79826)
#>  os       Windows 10 x64                                    
#>  system   x86_64, mingw32                                   
#>  ui       RTerm                                             
#>  language (EN)                                              
#>  collate  English_United States.1252                        
#>  ctype    English_United States.1252                        
#>  tz       Europe/Berlin                                     
#>  date     2021-02-12                                        
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version    date       lib source                                
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.1.0)                        
#>  backports     1.2.1      2020-12-09 [1] CRAN (R 4.1.0)                        
#>  cli           2.3.0      2021-01-31 [1] CRAN (R 4.1.0)                        
#>  colorspace    2.0-0      2020-11-11 [1] CRAN (R 4.1.0)                        
#>  crayon        1.4.1      2021-02-08 [1] CRAN (R 4.1.0)                        
#>  curl          4.3        2019-12-02 [1] CRAN (R 4.1.0)                        
#>  DBI           1.1.1      2021-01-15 [1] CRAN (R 4.1.0)                        
#>  digest        0.6.27     2020-10-24 [1] CRAN (R 4.1.0)                        
#>  dplyr         1.0.4      2021-02-02 [1] CRAN (R 4.1.0)                        
#>  ellipsis      0.3.1      2020-05-15 [1] CRAN (R 4.1.0)                        
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 4.1.0)                        
#>  farver        2.0.3      2020-01-16 [1] CRAN (R 4.1.0)                        
#>  fs            1.5.0      2020-07-31 [1] CRAN (R 4.1.0)                        
#>  generics      0.1.0      2020-10-31 [1] CRAN (R 4.1.0)                        
#>  ggplot2     * 3.3.3      2020-12-30 [1] CRAN (R 4.1.0)                        
#>  glue          1.4.2      2020-08-27 [1] CRAN (R 4.1.0)                        
#>  gtable        0.3.0      2019-03-25 [1] CRAN (R 4.1.0)                        
#>  highr         0.8        2019-03-20 [1] CRAN (R 4.1.0)                        
#>  htmltools     0.5.1.1    2021-01-22 [1] CRAN (R 4.1.0)                        
#>  httr          1.4.2      2020-07-20 [1] CRAN (R 4.1.0)                        
#>  knitr         1.31       2021-01-27 [1] CRAN (R 4.1.0)                        
#>  labeling      0.4.2      2020-10-20 [1] CRAN (R 4.1.0)                        
#>  lifecycle     0.2.0      2020-03-06 [1] CRAN (R 4.1.0)                        
#>  magrittr      2.0.1      2020-11-17 [1] CRAN (R 4.1.0)                        
#>  mime          0.9        2020-02-04 [1] CRAN (R 4.1.0)                        
#>  munsell       0.5.0      2018-06-12 [1] CRAN (R 4.1.0)                        
#>  pillar        1.4.7      2020-11-20 [1] CRAN (R 4.1.0)                        
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.1.0)                        
#>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.1.0)                        
#>  R6            2.5.0      2020-10-28 [1] CRAN (R 4.1.0)                        
#>  reprex        1.0.0      2021-01-27 [1] CRAN (R 4.1.0)                        
#>  rlang         0.4.10     2020-12-30 [1] CRAN (R 4.1.0)                        
#>  rmarkdown     2.6        2020-12-14 [1] CRAN (R 4.1.0)                        
#>  scales        1.1.1      2020-05-11 [1] CRAN (R 4.1.0)                        
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.1.0)                        
#>  stringi       1.5.3      2020-09-09 [1] CRAN (R 4.1.0)                        
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 4.1.0)                        
#>  styler        1.3.2.9000 2021-02-08 [1] Github (lorenzwalthert/styler@72b40e4)
#>  tibble        3.0.6      2021-01-29 [1] CRAN (R 4.1.0)                        
#>  tidyselect    1.1.0      2020-05-11 [1] CRAN (R 4.1.0)                        
#>  vctrs         0.3.6      2020-12-17 [1] CRAN (R 4.1.0)                        
#>  withr         2.4.1      2021-01-26 [1] CRAN (R 4.1.0)                        
#>  xfun          0.21       2021-02-10 [1] CRAN (R 4.1.0)                        
#>  xml2          1.3.2      2020-04-23 [1] CRAN (R 4.1.0)                        
#>  yaml          2.2.1      2020-02-01 [1] CRAN (R 4.1.0)                        
#> 
#> [1] C:/Users/inp099/Documents/R/win-library/4.1
#> [2] C:/Program Files/R/R-devel/library
```

</details>

**Comment by IndrajeetPatil** [comment]
Turns out this has nothing to do with the code I run. No matter which `ggplot` command I run, my session crashes. 

So there is something wrong with my machine itself, and not with `ggplot2`.

**Comment by IndrajeetPatil** [comment]
Turns out this was due to using `AGG` device in RStudio. 

To avoid this, you have two options:
- choose `Windows` graphics device in RStudio
- update to the `GitHub` version of `ragg` package

**Comment by katchristiansen** [comment]
How does one choose a Windows graphics device in RStudio, or update Github version of ragg? I am having this exact same problem, but only with some plots, and am at my wit's end!

**Comment by IndrajeetPatil** [comment]
You can find it `Tools -> Global tools`. That said, I am a bit surprised that you are encountering this issue, since it was fixed in the new version of `ragg`. Have you updated all of your packages and tried again?

<img width="738" alt="Screenshot 2021-03-05 at 15 11 04" src="https://user-images.githubusercontent.com/11330453/110126787-12a89700-7dc5-11eb-89cf-fc2945ea8254.png">

**Comment by katchristiansen** [comment]
Thank you, I updated my graphics to Windows and have updated all of my packages, including ragg, but still having the same problem when I use ggplot2, which seems to be after using the plan(multisession) function of the future package. I don't know if there is some sort of interference with this package in particular that causes ggplot2 to abort?

**Comment by IndrajeetPatil** [comment]
Hmm, in that case, I would say either ask this question on StackOverflow or RStudio community or open a new issue here.
Because this seems like a different issue than what I was facing.
